# Generated by Django 4.2.1 on 2023-06-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('network', '0001_custom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Данные поставщика',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('model', models.CharField(max_length=250, verbose_name='Модель')),
                ('release', models.DateField(verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('Администратор', 'Администратор'), ('Поставщик', 'Поставщик')],
                default='Поставщик',
                max_length=13,
                verbose_name='Роль',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(
                choices=[('m', 'Мужской'), ('f', 'Женский')], default='m', max_length=1, verbose_name='Пол'
            ),
        ),
    ]
