# Generated by Django 4.2.1 on 2023-06-02 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('network', '0002_contacts_product_alter_user_role_alter_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                (
                    'type_provider',
                    models.CharField(
                        choices=[
                            ('Factory', 'Завод'),
                            ('Retail', 'Розничная сеть'),
                            ('Individual', 'Индивидуальный предприниматель'),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name='Тип поставщика',
                    ),
                ),
                (
                    'credit',
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Задолженность кредиторская'),
                ),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                (
                    'lev',
                    models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], verbose_name='Уровень в сети'),
                ),
                (
                    'contacts',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='network.contacts',
                        verbose_name='Контактные данные',
                    ),
                ),
                ('products', models.ManyToManyField(to='network.product', verbose_name='Товары')),
                (
                    'self_provider',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='network.provider',
                        verbose_name='Поставщик',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
