# Generated by Django 4.2.1 on 2023-06-05 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('network', '0003_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Сотрудник',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Сотрудник',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Запись изменена'),
        ),
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Сотрудник',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='lev',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 0), (1, 1), (2, 2)], default=0, verbose_name='Уровень в сети'
            ),
        ),
        migrations.AlterField(
            model_name='provider',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Запись создана'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('Администратор', 'Администратор'), ('Сотрудник', 'Сотрудник')],
                default='Сотрудник',
                max_length=13,
                verbose_name='Роль',
            ),
        ),
    ]
